# Generated by Django 2.2.1 on 2019-05-01 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choice',
            new_name='Choix',
        ),
        migrations.RenameField(
            model_name='choix',
            old_name='choice_text',
            new_name='choix_text',
        ),
    ]
